/* Contenido de demostración. Sustituir por un CMS o colección de contenido al publicar. */
window.EL_APUNTE_ARTICLES = [
  { slug: "api-python-fastapi-postgresql", type: "Guía", cat: "backend", catLabel: "Backend", date: "24 sep 2026", minutes: 45, level: "Intermedio", title: "De cero a producción: tu primera API con Python, FastAPI y PostgreSQL", excerpt: "Una ruta completa para levantar una API pequeña, mantener secretos fuera del código y entender cada pieza." },
  { slug: "que-es-un-servidor", type: "Artículo", cat: "servidores", catLabel: "Servidores", date: "12 sep 2026", minutes: 8, level: "Principiante", title: "Qué es un servidor de verdad (no, no es una máquina mágica)", excerpt: "Un servidor es un proceso escuchando en un puerto. Desarmamos el mito y vemos cómo inspeccionar lo que corre en tu máquina." },
  { slug: "psycopg3-postgresql", type: "Tutorial", cat: "bd", catLabel: "Bases de datos", date: "08 sep 2026", minutes: 12, level: "Intermedio", title: "psycopg3: la conexión a PostgreSQL que no se cae a la primera", excerpt: "Pool de conexiones, consultas parametrizadas y errores frecuentes en proyectos escolares." },
  { slug: "websockets-fastapi", type: "Tutorial", cat: "web", catLabel: "Web", date: "03 sep 2026", minutes: 10, level: "Intermedio", title: "WebSockets sin dolor: chat en vivo con FastAPI", excerpt: "El handshake, el header Upgrade y mensajes a clientes conectados sin perderse en hilos." },
  { slug: "git-supervivencia", type: "Artículo", cat: "herramientas", catLabel: "Herramientas", date: "28 ago 2026", minutes: 7, level: "Principiante", title: "Git para sobrevivir la entrega de mañana", excerpt: "Los comandos esenciales para trabajar sin miedo: add, commit, branch, merge, stash y revert." },
  { slug: "tuneles-ngrok", type: "Tutorial", cat: "servidores", catLabel: "Servidores", date: "22 ago 2026", minutes: 9, level: "Principiante", title: "Túneles y ngrok: muestra tu proyecto local sin abrir puertos", excerpt: "Qué es un túnel inverso, cuándo usarlo y cuándo es mejor preparar un VPS." },
  { slug: "indices-postgresql", type: "Artículo", cat: "bd", catLabel: "Bases de datos", date: "15 ago 2026", minutes: 11, level: "Intermedio", title: "Índices en PostgreSQL: el truco de los 1000x que nadie explica", excerpt: "Por qué una consulta cambia radicalmente cuando eliges el índice correcto." },
  { slug: "variables-entorno", type: "Artículo", cat: "herramientas", catLabel: "Herramientas", date: "01 ago 2026", minutes: 6, level: "Principiante", title: "Variables de entorno: guarda tus contraseñas fuera del código", excerpt: "Una introducción práctica a .env, secretos y configuración por entorno." }
];
